name: Lint Code Base
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: riege/code-quality/.github/workflows/tflint.yml@main
    permissions:
      checks: write
